export const pacientesSeed = [
  // JUNIO
  { nombre: "Gabriel", apellido: "Castillo", lesion: "Entrenamiento", compradas: "-", disponibles: "-" },
  { nombre: "Carlos", apellido: "Caneva", lesion: "Entrenamiento", compradas: "-", disponibles: "-" },
  { nombre: "Natalia", apellido: "Polero", lesion: "Entrenamiento", compradas: "-", disponibles: "-" },
  { nombre: "Joaquín", apellido: "Cabrera", lesion: "Post op LCA", compradas: 10, disponibles: 0 },
  { nombre: "Marcelo", apellido: "Aurrecochea", lesion: "Hombro congelado + prótesis cadera", compradas: 15, disponibles: 0 },
  { nombre: "Noelia", apellido: "Medina", lesion: "Lumbalgia", compradas: 10, disponibles: 0 },
  { nombre: "Sebastián", apellido: "Godoy", lesion: "Tendinosis rotuliana", compradas: 5, disponibles: 0 },
  { nombre: "Carlos", apellido: "Pais", lesion: "Tendinosis aquiles", compradas: 1, disponibles: 0 },
  { nombre: "Guillermo", apellido: "López", lesion: "Artrosis pie", compradas: 5, disponibles: 1 },
  { nombre: "Fau", apellido: "Burgos", lesion: "Lagomar", compradas: 5, disponibles: "-" },
  { nombre: "Nicolás", apellido: "Bioñes", lesion: "Neuro", compradas: 10, disponibles: 1 },
  { nombre: "Ana", apellido: "Carabajal", lesion: "LCA (Lagomar)", compradas: 15, disponibles: "-" },
  { nombre: "Alejandro", apellido: "Rameau", lesion: "Rodilla tendinosis", compradas: 5, disponibles: 0 },
  { nombre: "Pablo", apellido: "Solís", lesion: "Cadera (Lagomar)", compradas: 10, disponibles: "-" },
  { nombre: "Daniel", apellido: "Paz", lesion: "Hombro congelado", compradas: 10, disponibles: 2 },
  { nombre: "Caro", apellido: "Hornos", lesion: "Desgarro gemelo (Lagomar)", compradas: 10, disponibles: "-" },
  { nombre: "Flor", apellido: "Tendinosis", lesion: "Tendinosis bíceps femoral (Lagomar)", compradas: 10, disponibles: "-" },
  { nombre: "Lu", apellido: "Desgarro", lesion: "Desgarro aductor (Lagomar)", compradas: 10, disponibles: "-" },
  { nombre: "Ana", apellido: "Varela", lesion: "Lagomar", compradas: 5, disponibles: "-" },
  { nombre: "Cecilia", apellido: "Sosa", lesion: "Lagomar", compradas: 10, disponibles: "-" },
  { nombre: "Sofía", apellido: "Ferreira", lesion: "Neuro", compradas: 15, disponibles: 6 },
  { nombre: "Santiago", apellido: "López", lesion: "Quiste Baker + edema óseo peroné", compradas: 10, disponibles: 5 },
  { nombre: "Mercedes", apellido: "Entrenamiento", lesion: "Entrenamiento", compradas: "-", disponibles: "-" },
  { nombre: "Welly", apellido: "Battro", lesion: "Entrenamiento", compradas: "-", disponibles: "-" },
  { nombre: "Matías", apellido: "Rodríguez", lesion: "Tendinosis rodilla y aquiles", compradas: 10, disponibles: 3 },
  { nombre: "Víctor", apellido: "Lamela", lesion: "Hombro / funcionalidad", compradas: 15, disponibles: 10 },
  { nombre: "María", apellido: "Lorenzo", lesion: "Post op LCA", compradas: 10, disponibles: 9 },
  { nombre: "Luana", apellido: "Valledor", lesion: "Ruptura LCP", compradas: "-", disponibles: 5 },
  { nombre: "Juanma", apellido: "Umpiérrez", lesion: "Tendinosis rodilla", compradas: 10, disponibles: 7 },
  { nombre: "Manuela", apellido: "Deal García", lesion: "Neuro", compradas: 15, disponibles: 13 },
  { nombre: "Nicolás", apellido: "Krell", lesion: "Muñeca y hombro (Lagomar)", compradas: 10, disponibles: "-" },
  { nombre: "María", apellido: "ACV", lesion: "ACV neuro", compradas: 10, disponibles: 6 },
  { nombre: "Mariana", apellido: "Esguince", lesion: "Esguince tobillo (Lagomar)", compradas: 10, disponibles: "-" },
  { nombre: "Natalia", apellido: "Schulkin", lesion: "Hombro-cuello-pierna", compradas: 10, disponibles: "-" },
  { nombre: "Marta", apellido: "Alexandra", lesion: "Domicilio Pinar", compradas: "-", disponibles: "-" },

  // JULIO
  { nombre: "Francisco", apellido: "Iriarte", lesion: "Tendinosis rotuliana y tríceps distal", compradas: 10, disponibles: 9 },
  { nombre: "Eric", apellido: "Zarsky", lesion: "Respiratorio - pectoral menor", compradas: 10, disponibles: 8 },
  { nombre: "Maichol", apellido: "Coton", lesion: "Lumbalgia", compradas: 10, disponibles: 9 },
  { nombre: "Marcelo", apellido: "Aurrecochea", lesion: "Cadera y hombro", compradas: 15, disponibles: 10 },
  { nombre: "Virginia", apellido: "Cervieri", lesion: "Gonalgia derecha", compradas: 10, disponibles: 8 },
  { nombre: "Daniel", apellido: "Alemán", lesion: "LCA", compradas: 8, disponibles: 5 },
  { nombre: "Gabriel", apellido: "Castillo", lesion: "Entrenamiento", compradas: "-", disponibles: 10 },
  { nombre: "Carlos", apellido: "Caneva", lesion: "Entrenamiento", compradas: "-", disponibles: 6 },
  { nombre: "Natalia", apellido: "Polero", lesion: "Entrenamiento", compradas: "-", disponibles: 6 },
  { nombre: "Bolívar", apellido: "Ruptura", lesion: "Ruptura LCA", compradas: 10, disponibles: 7 },
  { nombre: "Santino", apellido: "Ríos", lesion: "Rodilla menisco", compradas: 10, disponibles: 10 },
  { nombre: "Mauro", apellido: "Fernández", lesion: "Tendinosis bíceps y tibial post", compradas: 10, disponibles: 9 },
  { nombre: "Blanca", apellido: "Pocitos", lesion: "Domicilio Pocitos", compradas: 10, disponibles: "-" },
  { nombre: "Joaquín", apellido: "Cabrera", lesion: "Post op LCA", compradas: 10, disponibles: 10 },
  { nombre: "Noelia", apellido: "Lumbalgia", lesion: "Lumbalgia espalda", compradas: 5, disponibles: 5 },
  { nombre: "Alejandro", apellido: "Rameau", lesion: "Rodilla tendinosis", compradas: 5, disponibles: 5 },
  { nombre: "Sebastián", apellido: "Godoy", lesion: "Tendinosis rodilla", compradas: 5, disponibles: 5 },
];
