export const registrosMartinaSeed = [
  // MARTINA JULIO 2026
  // 1/7 Lunes - Domicilio Parque del Plata
  {
    fecha: "2026-07-01",
    email: "martuvz@gmail.com",
    paciente: "Kitty Alvez",
    tipo: "domicilio_b",
    horaInicio: "09:00",
    horaFin: "09:30",
    observaciones: "Domicilio Parque del Plata",
  },

  // 2/7 Clínica - 4 pacientes (2 por hora = 2 horas)
  {
    fecha: "2026-07-02",
    email: "martuvz@gmail.com",
    paciente: "Joaquín Cabrera",
    tipo: "clinica",
    horaInicio: "08:00",
    horaFin: "09:00",
    observaciones: "Post op LCA",
  },
  {
    fecha: "2026-07-02",
    email: "martuvz@gmail.com",
    paciente: "Guillermo López",
    tipo: "clinica",
    horaInicio: "08:00",
    horaFin: "09:00",
    observaciones: "Artrosis pie",
  },
  {
    fecha: "2026-07-02",
    email: "martuvz@gmail.com",
    paciente: "Mercedes",
    tipo: "clinica",
    horaInicio: "09:00",
    horaFin: "10:00",
    observaciones: "Entrenamiento",
  },
  {
    fecha: "2026-07-02",
    email: "martuvz@gmail.com",
    paciente: "Noelia Medina",
    tipo: "clinica",
    horaInicio: "09:00",
    horaFin: "10:00",
    observaciones: "Lumbalgia",
  },

  // 6/7 Lunes - Domicilio Parque del Plata
  {
    fecha: "2026-07-06",
    email: "martuvz@gmail.com",
    paciente: "Kitty Alvez",
    tipo: "domicilio_b",
    horaInicio: "14:00",
    horaFin: "14:30",
    observaciones: "Domicilio Parque del Plata",
  },

  // 7/7 Clínica Shangrila - 6 pacientes (2 por hora = 3 horas)
  {
    fecha: "2026-07-07",
    email: "martuvz@gmail.com",
    paciente: "María Lorenzo",
    tipo: "clinica",
    horaInicio: "08:00",
    horaFin: "09:00",
    observaciones: "Post op LCA - Clínica Shangrila",
  },
  {
    fecha: "2026-07-07",
    email: "martuvz@gmail.com",
    paciente: "Joaquín Cabrera",
    tipo: "clinica",
    horaInicio: "08:00",
    horaFin: "09:00",
    observaciones: "Post op LCA - Clínica Shangrila",
  },
  {
    fecha: "2026-07-07",
    email: "martuvz@gmail.com",
    paciente: "Manuela Deal García",
    tipo: "clinica",
    horaInicio: "09:00",
    horaFin: "10:00",
    observaciones: "Neuro - Clínica Shangrila",
  },
  {
    fecha: "2026-07-07",
    email: "martuvz@gmail.com",
    paciente: "Bolívar",
    tipo: "clinica",
    horaInicio: "09:00",
    horaFin: "10:00",
    observaciones: "Ruptura LCA - Clínica Shangrila",
  },
  {
    fecha: "2026-07-07",
    email: "martuvz@gmail.com",
    paciente: "Eric Zarsky",
    tipo: "clinica",
    horaInicio: "10:00",
    horaFin: "11:00",
    observaciones: "Respiratorio - Clínica Shangrila",
  },
  {
    fecha: "2026-07-07",
    email: "martuvz@gmail.com",
    paciente: "Noelia",
    tipo: "clinica",
    horaInicio: "10:00",
    horaFin: "11:00",
    observaciones: "Lumbalgia - Clínica Shangrila",
  },

  // 9/7 Jueves - Clínica Shangrila
  {
    fecha: "2026-07-09",
    email: "martuvz@gmail.com",
    paciente: "Alejandro Rameau",
    tipo: "clinica",
    horaInicio: "08:00",
    horaFin: "09:00",
    observaciones: "Rodilla tendinosis - Clínica Shangrila",
  },
  {
    fecha: "2026-07-09",
    email: "martuvz@gmail.com",
    paciente: "María Lorenzo",
    tipo: "clinica",
    horaInicio: "08:00",
    horaFin: "09:00",
    observaciones: "Post op LCA - Clínica Shangrila",
  },
  {
    fecha: "2026-07-09",
    email: "martuvz@gmail.com",
    paciente: "Noelia",
    tipo: "clinica",
    horaInicio: "09:00",
    horaFin: "10:00",
    observaciones: "Lumbalgia - Clínica Shangrila",
  },

  // Martes (8/7) - Clínica Shangrila
  {
    fecha: "2026-07-08",
    email: "martuvz@gmail.com",
    paciente: "Maichol Coton",
    tipo: "clinica",
    horaInicio: "08:00",
    horaFin: "09:00",
    observaciones: "Lumbalgia - Clínica Shangrila",
  },
  {
    fecha: "2026-07-08",
    email: "martuvz@gmail.com",
    paciente: "Noelia",
    tipo: "clinica",
    horaInicio: "08:00",
    horaFin: "09:00",
    observaciones: "Lumbalgia - Clínica Shangrila",
  },
  {
    fecha: "2026-07-08",
    email: "martuvz@gmail.com",
    paciente: "Mercedes",
    tipo: "clinica",
    horaInicio: "09:00",
    horaFin: "10:00",
    observaciones: "Entrenamiento - Clínica Shangrila",
  },
];
