-- Insertar TODOS los pacientes en Supabase
INSERT INTO pacientes (nombre, apellido, lesion, tipo, sesiones_compradas, sesiones_disponibles) VALUES
('Gabriel', 'Castillo', 'Entrenamiento', 'clinica', 10, 10),
('Carlos', 'Caneva', 'Entrenamiento', 'clinica', 10, 10),
('Natalia', 'Polero', 'Entrenamiento', 'clinica', 10, 10),
('Joaquín', 'Cabrera', 'Post op LCA', 'clinica', 10, 0),
('Marcelo', 'Aurrecochea', 'Hombro congelado + prótesis cadera', 'clinica', 15, 0),
('Noelia', 'Medina', 'Lumbalgia', 'clinica', 10, 0),
('Sebastián', 'Godoy', 'Tendinosis rotuliana', 'clinica', 5, 0),
('Carlos', 'Pais', 'Tendinosis aquiles', 'clinica', 1, 0),
('Guillermo', 'López', 'Artrosis pie', 'clinica', 5, 1),
('Fau', 'Burgos', 'Lagomar', 'clinica', 5, 0),
('Nicolás', 'Bioñes', 'Neuro', 'clinica', 10, 1),
('Ana', 'Carabajal', 'LCA (Lagomar)', 'clinica', 15, 0),
('Alejandro', 'Rameau', 'Rodilla tendinosis', 'clinica', 5, 0),
('Pablo', 'Solís', 'Cadera (Lagomar)', 'clinica', 10, 0),
('Daniel', 'Paz', 'Hombro congelado', 'clinica', 10, 2),
('Caro', 'Hornos', 'Desgarro gemelo (Lagomar)', 'clinica', 10, 0),
('Flor', 'Tendinosis', 'Tendinosis bíceps femoral (Lagomar)', 'clinica', 10, 0),
('Lu', 'Desgarro', 'Desgarro aductor (Lagomar)', 'clinica', 10, 0),
('Ana', 'Varela', 'Lagomar', 'clinica', 5, 0),
('Cecilia', 'Sosa', 'Lagomar', 'clinica', 10, 0),
('Sofía', 'Ferreira', 'Neuro', 'clinica', 15, 6),
('Santiago', 'López', 'Quiste Baker + edema óseo peroné', 'clinica', 10, 5),
('Mercedes', 'Entrenamiento', 'Entrenamiento', 'clinica', 10, 0),
('Welly', 'Battro', 'Entrenamiento', 'clinica', 10, 0),
('Matías', 'Rodríguez', 'Tendinosis rodilla y aquiles', 'clinica', 10, 3),
('Víctor', 'Lamela', 'Hombro / funcionalidad', 'clinica', 15, 10),
('María', 'Lorenzo', 'Post op LCA', 'clinica', 10, 9),
('Luana', 'Valledor', 'Ruptura LCP', 'clinica', 5, 5),
('Juanma', 'Umpiérrez', 'Tendinosis rodilla', 'clinica', 10, 7),
('Manuela', 'Deal García', 'Neuro', 'clinica', 15, 13),
('Nicolás', 'Krell', 'Muñeca y hombro (Lagomar)', 'clinica', 10, 0),
('María', 'ACV', 'ACV neuro', 'clinica', 10, 6),
('Mariana', 'Esguince', 'Esguince tobillo (Lagomar)', 'clinica', 10, 0),
('Natalia', 'Schulkin', 'Hombro-cuello-pierna', 'clinica', 10, 0),
('Marta', 'Alexandra', 'Domicilio Pinar', 'domicilio', 10, 0),
('Kitty', 'Alvez', 'Domicilio Parque del Plata', 'domicilio', 5, 3),
('Jorge', 'Suárez', 'Desgarro cuádriceps Lagomar', 'clinica', 5, 0),
('Martín', 'González', 'Post op de LCA', 'clinica', 10, 5),
('Cristina', 'Crovara', 'Escoliosis Lagomar', 'clinica', 10, 6),
('Francisco', 'Iriarte', 'Tendinosis rotuliana y tríceps distal', 'clinica', 10, 9),
('Eric', 'Zarsky', 'Respiratorio - pectoral menor', 'clinica', 10, 8),
('Maichol', 'Coton', 'Lumbalgia', 'clinica', 10, 9),
('Virginia', 'Cervieri', 'Gonalgia derecha', 'clinica', 10, 8),
('Daniel', 'Alemán', 'LCA', 'clinica', 8, 5),
('Bolívar', 'Ruptura', 'Ruptura LCA', 'clinica', 10, 7),
('Santino', 'Ríos', 'Rodilla menisco', 'clinica', 10, 10),
('Mauro', 'Fernández', 'Tendinosis bíceps y tibial post', 'clinica', 10, 9),
('Blanca', 'Pocitos', 'Domicilio Pocitos', 'domicilio', 10, 0),
('Noelia', 'Lumbalgia', 'Lumbalgia espalda', 'clinica', 5, 5);

-- Verificar que se insertaron todos
SELECT COUNT(*) as total_pacientes FROM pacientes;
